# netlify.toml

[build]
  # First install dependencies (so stripe gets pulled in)
  command = "npm install"
  # Then publish your static files
  publish = "clarity-checkout"
  # And bundle your functions from here
  functions = "clarity-checkout/netlify/functions"

[dev]
  command = "npm install"
  publish = "clarity-checkout"
  functions = "clarity-checkout/netlify/functions"
